package org.example.Vista;

import javax.swing.*;
public class VentanaMain {
    public JPanel LayoutPrincipal;
    public JPanel Layout;
    public JButton btnConfiguracion;
    public JButton btnHistorial;
    public JButton btnPedidoMain;
    public JButton btnCerrarSesion;
    public JLabel lblImagenUSuario;
    public JLabel lblNombreUser;
    public JPanel LayoutPago;
    public JTable tableHistorial;
    public JTable tablaListaPedido;
    public JTable tableProductoPedido;
    public JPanel LayoutP;
    public JSpinner spCantidadPedido;
    public JButton btnAgregarPedido;
    public JButton btnContinuarPedido;
    public JLabel lblNombreProducto;
    public JTable tablePago;
    public JLabel lblFechaPago;
    public JLabel lblTotalPago;
    public JButton btnFinalizarPago;
    public JPanel LayoutEmpresa;
    public JPanel LayoutPedidos;
    public JPanel LayoutHistorial;
    public JTextField txtNombreInfoP;
    public JButton btnActualizarInfoP;
    public JButton btnEliminarInfoP;
    public JPanel LayoutConfiguracion;
    public JPasswordField txtPassInfoP;
    public JTextField txtApellidosInfoP;
    public JTextField txtCorreoInfoP;
    public JScrollPane scrollProducto;
    public JScrollPane ScrollLista;
    public JScrollPane scrollPago;
    public JScrollPane scrollHistorial;
    public JComboBox<String> cbTamanio;
    public JLabel lblPrecioUnidad;
    public JLabel lblTotalPedido;
    public JButton btnVerDescripcion;
    public JTextArea txtDescripcion;
    public JPopupMenu pmDescripcion;
    public JScrollPane scrollDescripcion;
    public JLabel lblNombreProductoLista;
    public JButton btnQuitarPedido;
    public JLabel lblPrecioTotal;
    public JButton btnCancelarPago;
    public JPanel LayoutPedido;
}
